<?php

/**
 * @file
 * Contains yoast_seo related functions.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\yoast_seo_preview\Form\YoastSeoPreviewFormHandler;

/**
 * Implements hook_help().
 */
function yoast_seo_preview_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the yoast_seo_preview module.
    case 'help.page.yoast_seo_preview':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('SEO Preview') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_entity_type_alter().
 *
 * Sets the default yoast_seo_preview_form form handler to entity type node.
 *
 * @see \Drupal\Core\Entity\Annotation\EntityType
 */
function yoast_seo_preview_entity_type_alter(array &$entity_types) {
  /* @var $entity_types \Drupal\Core\Entity\EntityTypeInterface[] */
  $entity_types['node']->setHandlerClass('yoast_seo_preview_form', YoastSeoPreviewFormHandler::class);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function yoast_seo_preview_form_field_storage_config_edit_form_alter(&$form, FormStateInterface $form_state) {
  if ($form_state->getFormObject()->getEntity()->getType() === 'yoast_seo_preview') {
    // Hide the cardinality field.
    $form['cardinality_container']['#access'] = FALSE;
    $form['cardinality_container']['#disabled'] = TRUE;
  }
}
